### ISSUE TITLE
Should I use the API in Update Checkers?

### ISSUE THREAD

**Issue by Guichaguri** [citricsquid/widget#41]
Perhaps you don't want that for any reason...
The Update Checker will only check when the game (Minecraft) is starting.

**Comment by citricsquid** [comment]
That's an acceptable use case for the API. I believe there's already a
number of people building update checkers with the API.

As long as you don't build a system that automatically downloads the
updates via Curse (since visits to the download pages are how Curse is able
to pay for the author rewards) or a system that causes an unreasonable
amount of requests to the API then you're free to use it how you wish.

Please let me know if you have any other questions about the widget, or if
there's anything I can do to improve the API for your use case.

**Comment by Guichaguri** [comment]
Thank you.
