### ISSUE TITLE
Widget broke after Curse redirection change

### ISSUE THREAD

**Issue by SanAndreasP** [citricsquid/widget#44]
So, https://www.curse.com/mc-mods now redirects to https://www.curseforge.com/legacy/mc-mods, which doesn't exist.
With that every embedded widget breaks.

The new page is https://www.curseforge.com/minecraft for the curse pages (e.g. https://www.curseforge.com/minecraft/mc-mods/mb-battlegear-2)
I hope this is just a small fix by changing the URL somewhere, and not having to rewrite the crawler :S

**Comment by citricsquid** [comment]
This is, unfortunately, a breaking change and I was given no notice that this change was coming.

The widget will require a rewrite to work with the new curseforge website format, not just because the page format has changed but because the structure has changed too — releases are spread across multiple pages, therefore we'll need some sort of background processing to ensure that the service can cope with the significant increase in time taken to process each Curse project.

I don't have an ETA on how long it'll take to fix this. Hopefully a day, or a few, but at this point, I'm not sure as I have other obligations. I am going to deploy a temporary notice that will display in place of widgets explaining that the service is down until further notice.

**Comment by SanAndreasP** [comment]
I feared that would be the case. In the mean time I'll just put a link to the files page of my mods and wait patiently until the widget is fixed.

Thanks for your response :)

**Comment by citricsquid** [comment]
The widget is back online now, under a new domain -- [cfwidget.com](https://www.cfwidget.com) -- with a new backend that supports the new CurseForge site. Project data is updated every hour, independent of any requests, which should improve the service stability.

The codebase isn't open source (and I'm not sure if it ever will be) so I will probably remove this repository soon.

Let me know if you run into any issues with the new site; the api is now available at https://api.cfwidget.com and all old widget.mcf.li URLs should redirect, e.g:

https://widget.mcf.li//mc-mods/minecraft/224602-ancient-warfare-2.json -> https://api.cfwidget.com/mc-mods/minecraft/224602-ancient-warfare-2
